services:
  kexa:
    build: https://github.com/kexa-io/Kexa.git
    #image: innovtech/kexa
    container_name: kexa
    env_file:
      - .env
    environment:
      - DEBUG_LEVEL=TRACE
    volumes:
      - ~/.kube/kubeconfig.podman:/usr/src/config
      - ./config:/app/config
      - ./rules:/app/rules
    depends_on:
      bddpostgresql:
        condition: service_healthy

  bddpostgresql:
    image: postgres:latest
    container_name: bddpostgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admn45
      POSTGRES_DB: kexabdd
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./bddpostgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@domain.com
      PGADMIN_DEFAULT_PASSWORD: admn45
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      - ./pgadminservers/servers.json:/pgadmin4/servers.json
    depends_on:
      bddpostgresql:
        condition: service_healthy

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admn45
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=bddpostgresql
      - GF_DATABASE_NAME=kexabdd
      - GF_DATABASE_USER=admin
      - GF_DATABASE_PASSWORD=admn45
      - GF_DATABASE_SSL_MODE=disable
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana-dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana-dashboards/dashboards:/var/lib/grafana/dashboards
    user: "${UID}:${GID}"
    depends_on:
      bddpostgresql:
        condition: service_healthy
