services:
  kexa:
    #build: https://github.com/kexa-io/Kexa.git
    image: innovtech/kexa
    container_name: kexa
    env_file:
      - .env
    volumes:
      - ~/.kube/config:/usr/src/config
      - ./config:/app/config
      - ./rules:/app/rules
