- version: 1.0.0
  date: 05-16-2025
  alert:
    fatal:
      enabled: true
      type: 
        - log
        #- email
      to: 
        - myEmail@gmail.com
    error:
      enabled: true
      type: 
        - log
        #- email
      to: 
        - myEmail@gmail.com
    warning:
      enabled: true
      type: 
        - log
        #- email
      to:
        - myEmail@gmail.com
    info:
      enabled: true
      type: 
        - log
        #- email
      to: 
        - myEmail@gmail.com
    global:
      enabled: true
      type: 
        - log
      #  - email
      to: 
        - myEmail@gmail.com
      conditions:
        - level: 0
          min: 1
        - level: 1
          min: 1
        - level: 2
          min: 1
        - level: 3
          min: 1
  rules:
    #change the namespace name to your namespace
    - name: "namespace-exist-api-4urcloud"
      description : "this rules is to check if namespace exist and notifiable if exist"
      applied: true
      level: 1
      cloudProvider: kubernetes
      objectName : namespaces
      conditions:
        - property: .
          condition: SOME
          value:
            - property : metadata.name
              condition : EQUAL
              value : 4urcloud
    - name: "all-pods-exist-kexawebsite"
      description : "this rules is to check if all pods exist for a namespace"
      applied: true
      level: 1
      cloudProvider: kubernetes
      objectName : pods
      conditions:
        - property: .
          condition: SOME
          value:
            - operator: AND
              criteria:
                - property: metadata.name
                  condition: STARTS_WITH
                  value: kexawebsite
                - property: metadata.namespace
                  condition: EQUAL
                  value: 4urcloud
            - operator: AND
              criteria:
                - property: metadata.name
                  condition: STARTS_WITH
                  value: oauthinnovtech
                - property: metadata.namespace
                  condition: EQUAL
                  value: 4urcloud
            - operator: AND
              criteria:
                - property: metadata.name
                  condition: STARTS_WITH
                  value: web4urcloud
                - property: metadata.namespace
                  condition: EQUAL
                  value: 4urcloud
    - name: "all-pods-running-kexawebsite"
      description : "this rules is to check if all pods are running for a namespace"
      applied: true
      level: 1
      cloudProvider: kubernetes
      objectName : pods
      conditions:
        - operator: NAND
          criteria:
            - property : status.phase
              condition : DIFFERENT
              value : Running
            - property : metadata.namespace
              condition : EQUAL
              value : 4urcloud

    - name: "kube-is-persistent-volume-bounded"
      description : "this rules is to verify that persistent volume is bounded"
      applied: true
      level: 1
      cloudProvider: kubernetes
      objectName : persistentvolume
      conditions:
        - property : status.phase
          condition : EQUAL
          value : 'Bound'